from typing import Dict, Tuple

# First value is the value that it is serialized as
# Second value is the path to load it from
SERIALIZABLE_MAPPING: Dict[Tuple[str, ...], Tuple[str, ...]] = {
    ("langchain", "schema", "messages", "AIMessage"): (
        "sparkai",
        "core",
        "messages",
        "ai",
        "AIMessage",
    ),
    ("langchain", "schema", "messages", "AIMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "ai",
        "AIMessageChunk",
    ),
    ("langchain", "schema", "messages", "BaseMessage"): (
        "sparkai",
        "core",
        "messages",
        "base",
        "BaseMessage",
    ),
    ("langchain", "schema", "messages", "BaseMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "base",
        "BaseMessageChunk",
    ),
    ("langchain", "schema", "messages", "ChatMessage"): (
        "sparkai",
        "core",
        "messages",
        "chat",
        "ChatMessage",
    ),
    ("langchain", "schema", "messages", "FunctionMessage"): (
        "sparkai",
        "core",
        "messages",
        "function",
        "FunctionMessage",
    ),
    ("langchain", "schema", "messages", "HumanMessage"): (
        "sparkai",
        "core",
        "messages",
        "human",
        "HumanMessage",
    ),
    ("langchain", "schema", "messages", "SystemMessage"): (
        "sparkai",
        "core",
        "messages",
        "system",
        "SystemMessage",
    ),
    ("langchain", "schema", "messages", "ToolMessage"): (
        "sparkai",
        "core",
        "messages",
        "tool",
        "ToolMessage",
    ),
    ("langchain", "schema", "agent", "AgentAction"): (
        "sparkai",
        "core",
        "agents",
        "AgentAction",
    ),
    ("langchain", "schema", "agent", "AgentFinish"): (
        "sparkai",
        "core",
        "agents",
        "AgentFinish",
    ),
    ("langchain", "schema", "prompt_template", "BasePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "base",
        "BasePromptTemplate",
    ),
    ("langchain", "chains", "llm", "LLMChain"): (
        "sparkai",
        "core",
        "chains",
        "llm",
        "LLMChain",
    ),
    ("langchain", "prompts", "prompt", "PromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "prompt",
        "PromptTemplate",
    ),
    ("langchain", "prompts", "chat", "MessagesPlaceholder"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "MessagesPlaceholder",
    ),
    ("langchain", "llms", "openai", "OpenAI"): (
        "sparkai",
        "core",
        "llms",
        "base",
        "OpenAI",
    ),
    ("langchain", "prompts", "chat", "ChatPromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "ChatPromptTemplate",
    ),
    ("langchain", "prompts", "chat", "HumanMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "HumanMessagePromptTemplate",
    ),
    ("langchain", "prompts", "chat", "SystemMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "SystemMessagePromptTemplate",
    ),
    ("langchain", "schema", "agent", "AgentActionMessageLog"): (
        "sparkai",
        "core",
        "agents",
        "AgentActionMessageLog",
    ),
    ("langchain", "schema", "agent", "OpenAIToolAgentAction"): (
        "sparkai",
        "core",
        "agents",
        "output_parsers",
        "openai_tools",
        "OpenAIToolAgentAction",
    ),
    ("langchain", "prompts", "chat", "BaseMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "BaseMessagePromptTemplate",
    ),
    ("langchain", "schema", "output", "ChatGeneration"): (
        "sparkai",
        "core",
        "outputs",
        "chat_generation",
        "ChatGeneration",
    ),
    ("langchain", "schema", "output", "Generation"): (
        "sparkai",
        "core",
        "outputs",
        "generation",
        "Generation",
    ),
    ("langchain", "schema", "document", "Document"): (
        "sparkai",
        "core",
        "documents",
        "base",
        "Document",
    ),
    ("langchain", "output_parsers", "fix", "OutputFixingParser"): (
        "langchain",
        "output_parsers",
        "fix",
        "OutputFixingParser",
    ),
    ("langchain", "prompts", "chat", "AIMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "AIMessagePromptTemplate",
    ),
    ("langchain", "output_parsers", "regex", "RegexParser"): (
        "langchain",
        "output_parsers",
        "regex",
        "RegexParser",
    ),
    ("langchain", "schema", "runnable", "DynamicRunnable"): (
        "sparkai",
        "core",
        "runnables",
        "configurable",
        "DynamicRunnable",
    ),
    ("langchain", "schema", "prompt", "PromptValue"): (
        "sparkai",
        "core",
        "prompt_values",
        "PromptValue",
    ),
    ("langchain", "schema", "runnable", "RunnableBinding"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableBinding",
    ),
    ("langchain", "schema", "runnable", "RunnableBranch"): (
        "sparkai",
        "core",
        "runnables",
        "branch",
        "RunnableBranch",
    ),
    ("langchain", "schema", "runnable", "RunnableWithFallbacks"): (
        "sparkai",
        "core",
        "runnables",
        "fallbacks",
        "RunnableWithFallbacks",
    ),
    ("langchain", "schema", "output_parser", "StrOutputParser"): (
        "sparkai",
        "core",
        "output_parsers",
        "string",
        "StrOutputParser",
    ),
    ("langchain", "chat_models", "openai", "ChatOpenAI"): (
        "langchain_openai",
        "chat_models",
        "base",
        "ChatOpenAI",
    ),
    ("langchain", "output_parsers", "list", "CommaSeparatedListOutputParser"): (
        "sparkai",
        "core",
        "output_parsers",
        "list",
        "CommaSeparatedListOutputParser",
    ),
    ("langchain", "schema", "runnable", "RunnableParallel"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableParallel",
    ),
    ("langchain", "chat_models", "azure_openai", "AzureChatOpenAI"): (
        "langchain_openai",
        "chat_models",
        "azure",
        "AzureChatOpenAI",
    ),
    ("langchain", "chat_models", "bedrock", "BedrockChat"): (
        "langchain",
        "chat_models",
        "bedrock",
        "BedrockChat",
    ),
    ("langchain", "chat_models", "anthropic", "ChatAnthropic"): (
        "langchain",
        "chat_models",
        "anthropic",
        "ChatAnthropic",
    ),
    ("langchain", "chat_models", "fireworks", "ChatFireworks"): (
        "langchain",
        "chat_models",
        "fireworks",
        "ChatFireworks",
    ),
    ("langchain", "chat_models", "google_palm", "ChatGooglePalm"): (
        "langchain",
        "chat_models",
        "google_palm",
        "ChatGooglePalm",
    ),
    ("langchain", "chat_models", "vertexai", "ChatVertexAI"): (
        "langchain_google_vertexai",
        "chat_models",
        "ChatVertexAI",
    ),
    ("langchain", "schema", "output", "ChatGenerationChunk"): (
        "sparkai",
        "core",
        "outputs",
        "chat_generation",
        "ChatGenerationChunk",
    ),
    ("langchain", "schema", "messages", "ChatMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "chat",
        "ChatMessageChunk",
    ),
    ("langchain", "schema", "messages", "HumanMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "human",
        "HumanMessageChunk",
    ),
    ("langchain", "schema", "messages", "FunctionMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "function",
        "FunctionMessageChunk",
    ),
    ("langchain", "schema", "messages", "SystemMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "system",
        "SystemMessageChunk",
    ),
    ("langchain", "schema", "messages", "ToolMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "tool",
        "ToolMessageChunk",
    ),
    ("langchain", "schema", "output", "GenerationChunk"): (
        "sparkai",
        "core",
        "outputs",
        "generation",
        "GenerationChunk",
    ),
    ("langchain", "llms", "openai", "BaseOpenAI"): (
        "langchain",
        "llms",
        "openai",
        "BaseOpenAI",
    ),
    ("langchain", "llms", "bedrock", "Bedrock"): (
        "langchain",
        "llms",
        "bedrock",
        "Bedrock",
    ),
    ("langchain", "llms", "fireworks", "Fireworks"): (
        "langchain",
        "llms",
        "fireworks",
        "Fireworks",
    ),
    ("langchain", "llms", "google_palm", "GooglePalm"): (
        "langchain",
        "llms",
        "google_palm",
        "GooglePalm",
    ),
    ("langchain", "llms", "openai", "AzureOpenAI"): (
        "langchain_openai",
        "llms",
        "azure",
        "AzureOpenAI",
    ),
    ("langchain", "llms", "replicate", "Replicate"): (
        "langchain",
        "llms",
        "replicate",
        "Replicate",
    ),
    ("langchain", "llms", "vertexai", "VertexAI"): (
        "langchain_vertexai",
        "llms",
        "VertexAI",
    ),
    ("langchain", "output_parsers", "combining", "CombiningOutputParser"): (
        "langchain",
        "output_parsers",
        "combining",
        "CombiningOutputParser",
    ),
    ("langchain", "schema", "prompt_template", "BaseChatPromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "BaseChatPromptTemplate",
    ),
    ("langchain", "prompts", "chat", "ChatMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "ChatMessagePromptTemplate",
    ),
    ("langchain", "prompts", "few_shot_with_templates", "FewShotPromptWithTemplates"): (
        "sparkai",
        "core",
        "prompts",
        "few_shot_with_templates",
        "FewShotPromptWithTemplates",
    ),
    ("langchain", "prompts", "pipeline", "PipelinePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "pipeline",
        "PipelinePromptTemplate",
    ),
    ("langchain", "prompts", "base", "StringPromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "string",
        "StringPromptTemplate",
    ),
    ("langchain", "prompts", "base", "StringPromptValue"): (
        "sparkai",
        "core",
        "prompt_values",
        "StringPromptValue",
    ),
    ("langchain", "prompts", "chat", "BaseStringMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "BaseStringMessagePromptTemplate",
    ),
    ("langchain", "prompts", "chat", "ChatPromptValue"): (
        "sparkai",
        "core",
        "prompt_values",
        "ChatPromptValue",
    ),
    ("langchain", "prompts", "chat", "ChatPromptValueConcrete"): (
        "sparkai",
        "core",
        "prompt_values",
        "ChatPromptValueConcrete",
    ),
    ("langchain", "schema", "runnable", "HubRunnable"): (
        "langchain",
        "runnables",
        "hub",
        "HubRunnable",
    ),
    ("langchain", "schema", "runnable", "RunnableBindingBase"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableBindingBase",
    ),
    ("langchain", "schema", "runnable", "OpenAIFunctionsRouter"): (
        "langchain",
        "runnables",
        "openai_functions",
        "OpenAIFunctionsRouter",
    ),
    ("langchain", "schema", "runnable", "RouterRunnable"): (
        "sparkai",
        "core",
        "runnables",
        "router",
        "RouterRunnable",
    ),
    ("langchain", "schema", "runnable", "RunnablePassthrough"): (
        "sparkai",
        "core",
        "runnables",
        "passthrough",
        "RunnablePassthrough",
    ),
    ("langchain", "schema", "runnable", "RunnableSequence"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableSequence",
    ),
    ("langchain", "schema", "runnable", "RunnableEach"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableEach",
    ),
    ("langchain", "schema", "runnable", "RunnableEachBase"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableEachBase",
    ),
    ("langchain", "schema", "runnable", "RunnableConfigurableAlternatives"): (
        "sparkai",
        "core",
        "runnables",
        "configurable",
        "RunnableConfigurableAlternatives",
    ),
    ("langchain", "schema", "runnable", "RunnableConfigurableFields"): (
        "sparkai",
        "core",
        "runnables",
        "configurable",
        "RunnableConfigurableFields",
    ),
    ("langchain", "schema", "runnable", "RunnableWithMessageHistory"): (
        "sparkai",
        "core",
        "runnables",
        "history",
        "RunnableWithMessageHistory",
    ),
    ("langchain", "schema", "runnable", "RunnableAssign"): (
        "sparkai",
        "core",
        "runnables",
        "passthrough",
        "RunnableAssign",
    ),
    ("langchain", "schema", "runnable", "RunnableRetry"): (
        "sparkai",
        "core",
        "runnables",
        "retry",
        "RunnableRetry",
    ),
}

# Needed for backwards compatibility for old versions of LangChain where things
# Were in different place
_OG_SERIALIZABLE_MAPPING: Dict[Tuple[str, ...], Tuple[str, ...]] = {
    ("langchain", "schema", "AIMessage"): (
        "sparkai",
        "core",
        "messages",
        "ai",
        "AIMessage",
    ),
    ("langchain", "schema", "ChatMessage"): (
        "sparkai",
        "core",
        "messages",
        "chat",
        "ChatMessage",
    ),
    ("langchain", "schema", "FunctionMessage"): (
        "sparkai",
        "core",
        "messages",
        "function",
        "FunctionMessage",
    ),
    ("langchain", "schema", "HumanMessage"): (
        "sparkai",
        "core",
        "messages",
        "human",
        "HumanMessage",
    ),
    ("langchain", "schema", "SystemMessage"): (
        "sparkai",
        "core",
        "messages",
        "system",
        "SystemMessage",
    ),
}

# Needed for backwards compatibility for a few versions where we serialized
# with langchain_core paths.
OLD_CORE_NAMESPACES_MAPPING: Dict[Tuple[str, ...], Tuple[str, ...]] = {
    ("sparkai",
     "core", "messages", "ai", "AIMessage"): (
        "sparkai",
        "core",
        "messages",
        "ai",
        "AIMessage",
    ),
    ("sparkai",
     "core", "messages", "ai", "AIMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "ai",
        "AIMessageChunk",
    ),
    ("sparkai",
     "core", "messages", "base", "BaseMessage"): (
        "sparkai",
        "core",
        "messages",
        "base",
        "BaseMessage",
    ),
    ("sparkai",
     "core", "messages", "base", "BaseMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "base",
        "BaseMessageChunk",
    ),
    ("sparkai",
     "core", "messages", "chat", "ChatMessage"): (
        "sparkai",
        "core",
        "messages",
        "chat",
        "ChatMessage",
    ),
    ("sparkai",
     "core", "messages", "function", "FunctionMessage"): (
        "sparkai",
        "core",
        "messages",
        "function",
        "FunctionMessage",
    ),
    ("sparkai",
     "core", "messages", "human", "HumanMessage"): (
        "sparkai",
        "core",
        "messages",
        "human",
        "HumanMessage",
    ),
    ("sparkai",
     "core", "messages", "system", "SystemMessage"): (
        "sparkai",
        "core",
        "messages",
        "system",
        "SystemMessage",
    ),
    ("sparkai",
     "core", "messages", "tool", "ToolMessage"): (
        "sparkai",
        "core",
        "messages",
        "tool",
        "ToolMessage",
    ),
    ("sparkai",
     "core", "agents", "AgentAction"): (
        "sparkai",
        "core",
        "agents",
        "AgentAction",
    ),
    ("sparkai",
     "core", "agents", "AgentFinish"): (
        "sparkai",
        "core",
        "agents",
        "AgentFinish",
    ),
    ("sparkai",
     "core", "prompts", "base", "BasePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "base",
        "BasePromptTemplate",
    ),
    ("sparkai",
     "core", "prompts", "prompt", "PromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "prompt",
        "PromptTemplate",
    ),
    ("sparkai",
     "core", "prompts", "chat", "MessagesPlaceholder"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "MessagesPlaceholder",
    ),
    ("sparkai",
     "core", "prompts", "chat", "ChatPromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "ChatPromptTemplate",
    ),
    ("sparkai",
     "core", "prompts", "chat", "HumanMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "HumanMessagePromptTemplate",
    ),
    ("sparkai",
     "core", "prompts", "chat", "SystemMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "SystemMessagePromptTemplate",
    ),
    ("sparkai",
     "core", "agents", "AgentActionMessageLog"): (
        "sparkai",
        "core",
        "agents",
        "AgentActionMessageLog",
    ),
    ("sparkai",
     "core", "prompts", "chat", "BaseMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "BaseMessagePromptTemplate",
    ),
    ("sparkai",
     "core", "outputs", "chat_generation", "ChatGeneration"): (
        "sparkai",
        "core",
        "outputs",
        "chat_generation",
        "ChatGeneration",
    ),
    ("sparkai",
     "core", "outputs", "generation", "Generation"): (
        "sparkai",
        "core",
        "outputs",
        "generation",
        "Generation",
    ),
    ("sparkai",
     "core", "documents", "base", "Document"): (
        "sparkai",
        "core",
        "documents",
        "base",
        "Document",
    ),
    ("sparkai",
     "core", "prompts", "chat", "AIMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "AIMessagePromptTemplate",
    ),
    ("sparkai",
     "core", "runnables", "configurable", "DynamicRunnable"): (
        "sparkai",
        "core",
        "runnables",
        "configurable",
        "DynamicRunnable",
    ),
    ("sparkai",
     "core", "prompt_values", "PromptValue"): (
        "sparkai",
        "core",
        "prompt_values",
        "PromptValue",
    ),
    ("sparkai",
     "core", "runnables", "base", "RunnableBinding"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableBinding",
    ),
    ("sparkai",
     "core", "runnables", "branch", "RunnableBranch"): (
        "sparkai",
        "core",
        "runnables",
        "branch",
        "RunnableBranch",
    ),
    ("sparkai",
     "core", "runnables", "fallbacks", "RunnableWithFallbacks"): (
        "sparkai",
        "core",
        "runnables",
        "fallbacks",
        "RunnableWithFallbacks",
    ),
    ("sparkai",
     "core", "output_parsers", "string", "StrOutputParser"): (
        "sparkai",
        "core",
        "output_parsers",
        "string",
        "StrOutputParser",
    ),
    ("sparkai",
     "core", "output_parsers", "list", "CommaSeparatedListOutputParser"): (
        "sparkai",
        "core",
        "output_parsers",
        "list",
        "CommaSeparatedListOutputParser",
    ),
    ("sparkai",
     "core", "runnables", "base", "RunnableParallel"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableParallel",
    ),
    ("sparkai",
     "core", "outputs", "chat_generation", "ChatGenerationChunk"): (
        "sparkai",
        "core",
        "outputs",
        "chat_generation",
        "ChatGenerationChunk",
    ),
    ("sparkai",
     "core", "messages", "chat", "ChatMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "chat",
        "ChatMessageChunk",
    ),
    ("sparkai",
     "core", "messages", "human", "HumanMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "human",
        "HumanMessageChunk",
    ),
    ("sparkai",
     "core", "messages", "function", "FunctionMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "function",
        "FunctionMessageChunk",
    ),
    ("sparkai",
     "core", "messages", "system", "SystemMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "system",
        "SystemMessageChunk",
    ),
    ("sparkai",
     "core", "messages", "tool", "ToolMessageChunk"): (
        "sparkai",
        "core",
        "messages",
        "tool",
        "ToolMessageChunk",
    ),
    ("sparkai",
     "core", "outputs", "generation", "GenerationChunk"): (
        "sparkai",
        "core",
        "outputs",
        "generation",
        "GenerationChunk",
    ),
    ("sparkai",
     "core", "prompts", "chat", "BaseChatPromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "BaseChatPromptTemplate",
    ),
    ("sparkai",
     "core", "prompts", "chat", "ChatMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "ChatMessagePromptTemplate",
    ),
    (
        "sparkai",
        "core",
        "prompts",
        "few_shot_with_templates",
        "FewShotPromptWithTemplates",
    ): (
        "sparkai",
        "core",
        "prompts",
        "few_shot_with_templates",
        "FewShotPromptWithTemplates",
    ),
    ("sparkai",
     "core", "prompts", "pipeline", "PipelinePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "pipeline",
        "PipelinePromptTemplate",
    ),
    ("sparkai",
     "core", "prompts", "string", "StringPromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "string",
        "StringPromptTemplate",
    ),
    ("sparkai",
     "core", "prompt_values", "StringPromptValue"): (
        "sparkai",
        "core",
        "prompt_values",
        "StringPromptValue",
    ),
    ("sparkai",
     "core", "prompts", "chat", "BaseStringMessagePromptTemplate"): (
        "sparkai",
        "core",
        "prompts",
        "chat",
        "BaseStringMessagePromptTemplate",
    ),
    ("sparkai",
     "core", "prompt_values", "ChatPromptValue"): (
        "sparkai",
        "core",
        "prompt_values",
        "ChatPromptValue",
    ),
    ("sparkai",
     "core", "prompt_values", "ChatPromptValueConcrete"): (
        "sparkai",
        "core",
        "prompt_values",
        "ChatPromptValueConcrete",
    ),
    ("sparkai",
     "core", "runnables", "base", "RunnableBindingBase"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableBindingBase",
    ),
    ("sparkai",
     "core", "runnables", "router", "RouterRunnable"): (
        "sparkai",
        "core",
        "runnables",
        "router",
        "RouterRunnable",
    ),
    ("sparkai",
     "core", "runnables", "passthrough", "RunnablePassthrough"): (
        "sparkai",
        "core",
        "runnables",
        "passthrough",
        "RunnablePassthrough",
    ),
    ("sparkai",
     "core", "runnables", "base", "RunnableSequence"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableSequence",
    ),
    ("sparkai",
     "core", "runnables", "base", "RunnableEach"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableEach",
    ),
    ("sparkai",
     "core", "runnables", "base", "RunnableEachBase"): (
        "sparkai",
        "core",
        "runnables",
        "base",
        "RunnableEachBase",
    ),
    (
        "sparkai",
        "core",
        "runnables",
        "configurable",
        "RunnableConfigurableAlternatives",
    ): (
        "sparkai",
        "core",
        "runnables",
        "configurable",
        "RunnableConfigurableAlternatives",
    ),
    ("sparkai",
     "core", "runnables", "configurable", "RunnableConfigurableFields"): (
        "sparkai",
        "core",
        "runnables",
        "configurable",
        "RunnableConfigurableFields",
    ),
    ("sparkai",
     "core", "runnables", "history", "RunnableWithMessageHistory"): (
        "sparkai",
        "core",
        "runnables",
        "history",
        "RunnableWithMessageHistory",
    ),
    ("sparkai",
     "core", "runnables", "passthrough", "RunnableAssign"): (
        "sparkai",
        "core",
        "runnables",
        "passthrough",
        "RunnableAssign",
    ),
    ("sparkai",
     "core", "runnables", "retry", "RunnableRetry"): (
        "sparkai",
        "core",
        "runnables",
        "retry",
        "RunnableRetry",
    ),
}
